version: 2
updates:

  # Maintain dependencies for GitHub Actions 
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10 
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps): "

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10 
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps): "